AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Layout:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true

Metrics:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
