plugins:
 - rubocop-on-rbs

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Layout:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true

Metrics:
  Enabled: false

Naming/PredicateMethod:
  Exclude:
    - 'lib/easytest/runner.rb'

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
