module Easytest
  class CLI
    SUCCESS: Integer

    FAILURE: Integer

    FATAL: Integer

    def run: () -> Integer

    private

    attr_reader argv: Array[String]

    attr_reader start_time: Time

    attr_reader options: Hash[Symbol, bool]

    attr_reader parser: OptionParser

    def initialize: (Array[String] argv) -> void

    def init_parser: () -> OptionParser

    def parse_argv: () -> Integer?

    def help: () -> String

    def setup: () -> void

    def load_test_file: (String file) -> void

    def test_files: () -> Array[String]

    def watch?: () -> bool

    def watch_files: () -> void
  end
end
