module Easytest
  class Error < StandardError
  end

  class FatalError < Error
  end

  class MatchError < Error
    attr_reader actual: untyped

    attr_reader expected: untyped

    def initialize: (message: untyped, actual: untyped, expected: untyped) -> void
  end
end
