module Easytest
  module Utils
    def self?.terminal_hyperlink: (String absolute_path) -> String

    def self?.raise_if_no_test_name: (String name, method: String) -> void

    def self?.pluralize: (String singular, Integer count) -> String

    def self?.indent_text: (String text, String indent_string) -> String
  end
end
