module Easytest
  module Matcher
    class Base[A, E]
      attr_reader actual: A

      attr_reader expected: E

      attr_reader negate: bool

      alias negate? negate

      def initialize: (actual: A, expected: E, ?negate: bool) -> void

      def match?: () -> bool

      def match!: () -> void

      private

      def message: () -> String

      def build_error_message: () -> String

      def raise_match_error: () -> void
    end
  end
end
