name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    uses: ybiquitous/.github/.github/workflows/ruby-test-reusable.yml@46e5ee1d74cc40a0448a372e22cf3e5852efd59a # v3.0.2
    with:
      minimum-ruby-version: 3.2 # sync with `required_ruby_version` in gemspec
    permissions:
      contents: read
