name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    uses: ybiquitous/.github/.github/workflows/ruby-test-reusable.yml@cdefa43486604b3aae79e9d1db24b670475f2c92 # v3.2.0
    with:
      minimum-ruby-version: 3.2 # sync with `required_ruby_version` in gemspec
    permissions:
      contents: read
