name: Release

on:
  workflow_dispatch:

jobs:
  release:
    # TODO: Try the new release workflow on main. Once it is verified, switch to a published version.
    uses: ybiquitous/.github/.github/workflows/ruby-release-reusable.yml@464d5df6b18ccf076a6a499ad87f4a853e5ba40b # main
    permissions:
      contents: write
      id-token: write
